### PR TITLE
Issue 22: archived phase

### PR DESCRIPTION
**Pull request by adrpar**
This needs thorough testing, not sure if I broke something.

And I have no UWS 1.1 service to test this. @kristinriebe maybe you can test the client still works and if you know a UWS 1.1 service, try filtering phase statuses still works?

### CODE REVIEW

**Comment by adrpar** [comment]
filtering defaults back to client side filtering (even if the filter has been applied on UWS 1.1 endpoint side. better be safe than sorry, but maybe we can check the service version here? need to think again)

**Comment by kristinriebe** [comment]
Finally finished some tests, it took some time to find working UWS1.1 servers and fix some other bugs before I could test this properly. Result: the server-side phase-filtering is not yet working.  
Two problems in `connection.py`, function `Connection.get()`:  
* `params` is not correct, the phase should not be a list, but a single string, e.g. "PHASE=ERROR".  
* The request parameters are not passed correctly by self.connection.request("GET", self.base_path, params, headers=self.headers). Something like this:
`self.connection.request("GET", self.base_path+'?'+params, headers=self.headers) does work, but I don't understand enough of httplib to see how to do it properly. 

I still need to test what happens when appending multiple filters; looks like the UWS1.1 service I use for checking does not do it correctly anyway.

**Comment by kristinriebe** [comment]
Okay, from the documentation on [HTTPConnection.request](https://docs.python.org/2/library/httplib.html): "[...] methods that expect a body (PUT, POST, and PATCH) [...]", I understand that the library just does not expect any parameters for the GET method and thus ignores them when setting them with `body=params` inside request. So either we use a different library (e.g. `requests`) or we append the parameters directly to the path. That's what I did in the commited version.  

I also changed the params-dictionary to a list of tuples. Server-side filtering now works e.g for following (partially 1.1-compliant) host: `http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/tap/auth-async`. Ask me if you want a working example for job submission. The host needs authentication, so you can either get your own account via their [registration page](http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/login.html) or you send me a mail for my credentials (don't want to put them here publicly).

**Comment by adrpar** [comment]
If it works now, I'm fine with your changes (though I thought that the params list would do what the UWS service needs. Apparently not). The strict UWS 1.1 mode I also think is a good idea, however can be a different ticket.

Further I would be happy to move to the requests library, now it should be able to do everything we need (at the time I wrote the client it was not yet there)

**Comment by adrpar** [comment]
If you are fine with it, you can merge this

**Pull request merged**
